### ISSUE TITLE
读取数据库配置错误

### ISSUE THREAD

**Issue by cfanboy** [mixstart/delayer#2]
在配置文件中指定非0的数据库无效，经查找发现：
config.go Line 56:

database, _ := delayer.Key("database").Int()

应该为：
database, _ := redis.Key("database").Int()

**Comment by onanying** [comment]
@cfanboy 已经修复 https://github.com/mix-basic/delayer/releases/tag/v1.0.4

**Comment by cfanboy** [comment]
maxIdle、maxActive、idleTimeout、connMaxLifetime
和database一样是错的 #_#

**Comment by onanying** [comment]
@cfanboy 好了好了，都改了，哈哈

**Comment by cfanboy** [comment]
哈哈，迅速^_^
