### ISSUE TITLE
项目运行几天后报错

### ISSUE THREAD

**Issue by Fleey** [mixstart/delayer#3]
[error] 2019/10/03 10:09:22 FAILURE: func getJobTopic, redigo: connection pool exhausted, [74f9584aaa0eaaeb2353d3c7d3b09c63].

**Comment by onanying** [comment]
错误都告诉你了，连接池没连接用了，你到配置文件 https://github.com/mix-basic/delayer/blob/master/delayer.conf 里调整连接池相关的参数

**Comment by Fleey** [comment]
问题早已解决，当天就发现是官方提供的PHP delayer包有问题。。。用完没close导致的

**Comment by onanying** [comment]
PHP delayer包和其他php类一样，是析构时会自己回收，你应该是没有让对象析构吧？
