### ISSUE TITLE
服务端是否支持多实例部署

### ISSUE THREAD

**Issue by herugen** [mixstart/delayer#5]
您好，从代码看，timer在读取redis获取超时任务的时候没看到利用redis上锁的逻辑，是否意味着服务端不支持多实例部署？

**Comment by onanying** [comment]
@TheWayYouMakeMeFeel  可以，但是没有这个必要啊

[delayer]
pid = /var/run/delayer.pid      ; 需单例执行时配置, 多实例执行时留空, Win不支持单例
